/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./components/**/*.{vue,js}",
		"./layouts/**/*.vue",
		"./pages/**/*.vue",
		"./app/app.vue",
		"./plugins/**/*.{js,ts}",
	],
	theme: {
        screens: {
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1280px",
            "1xl": "1365px",
            "1.5xl": "1440px",
            "2xl": "1536px",
            "3xl": "1599px",
            "3md": "1631px",
            "3lg": "1746px",
            "4xl": "1800px",
            "5xl": "2100px",
            "6xl": "2800px",
        },
        colors: ({ colors }) => ({
            primary: "#1E3A8A", // nadpisujesz lub dodajesz nowe kolory
            secondary: "#9333EA",
            accent: "#F59E0B",
            amber: colors.amber,
            black: "#000",
            black: colors.black,
            blue: colors.blue,
            chambray: "#515C6F",
            cream: "#faf9f5",
            current: colors.current,
            cyan: colors.cyan,
            dimGray: "#707070",
            emerald: colors.emerald,
            floralWhite: "#F9F8F4",
            fuchsia: colors.fuchsia,
            gainsboro: "#DFDFDF",
            glacier: "#78BBC5",
            gray: colors.gray,
            green: colors.green,
            hippiePink: "#AB464A",
            inactive: "#d6d7d7",
            indigo: colors.indigo,
            inherit: colors.inherit,
            inputBg: "#ebebe4",
            lightGray: "#D4D4D4",
            lightningYellow: "#FFA22F",
            lime: colors.lime,
            matterhorn: "#515151",
            neutral: colors.neutral,
            orange: colors.orange,
            pink: colors.pink,
            pinkSwan: "#b5b5b5",
            placeholder: "#718096ab",
            purple: colors.purple,
            red: colors.red,
            rose: colors.rose,
            sky: colors.sky,
            slate: colors.slate,
            stone: colors.stone,
            submarine: "#85989C",
            teal: colors.teal,
            transparent: "transparent",
            transparent: colors.transparent,
            tropicalRainForest: "#0C6A58",
            violet: colors.violet,
            whisper: "#E6E6E6",
            white: "#fff",
            white: colors.white,
            whiteSmoke: "#F8F8F8",
            yellow: colors.yellow,
            zinc: colors.zinc,
        }),
        fontFamily: {
            sans: ["Inter", "sans-serif"],
        },
		extend: {
		},
	},
	plugins: [],
};
